apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-manager
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: letsencrypt-job
  labels:
    app: letsencrypt
spec:
  schedule: "0 2 * * 1/3" 
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 120
  jobTemplate:
    spec:
      template:
        metadata:
          name: letsencrypt
          annotations:
            cloud.google.com/service-account: "certbot-dns-manager@k8s-dice-magic.iam.gserviceaccount.com"
          labels:
            app: letsencrypt
        spec:
          serviceAccountName: secret-manager
          containers:
          - image: gcr.io/k8s-dice-magic/letsencrypt-dev:latest
            name: letsencrypt
            imagePullPolicy: Always
            ports:
            - name: letsencrypt
              containerPort: 8080
            volumeMounts:
            - mountPath: /etc/certbot-dns
              name: certbot-dns
              readOnly: true
            envFrom:
            - configMapRef:
                name: certbot-config
            securityContext:
              privileged: false
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              capabilities:
                drop: ["ALL"]
          restartPolicy: Never
          volumes:
          - name: certbot-dns
            secret:
              defaultMode: 420
              secretName: certbot-dns 
      backoffLimit: 0
---
apiVersion: v1
kind: Secret
metadata:
  name: letsencrypt-certs
type: Opaque